#ifndef CONOSCOPELIB_GLOBAL_H
#define CONOSCOPELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONOSCOPELIB_LIBRARY)
#  define CONOSCOPELIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONOSCOPELIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONOSCOPELIB_GLOBAL_H
